[package]
name = "hardware-measurement"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
hidapi = "2.6.3"
nusb = { version = "0.2.1", features = ["tokio"] }
tokio = { version = "1.48.0", features = ["full"] }
async-trait = "0.1.89"